import os
import logging
from datetime import datetime
from fpdf import FPDF

REPORT_TRANSLATIONS = {
    # 1. Header
    "title": {"en": "AgriNova – Farmer Technology Adoption Report", "ta": "AgriNova – விவசாய தொழில்நுட்ப ஏற்றுக்கொள்ளல் அறிக்கை"},
    "farmer": {"en": "Farmer", "ta": "விவசாயி"},
    "district": {"en": "District", "ta": "மாவட்டம்"},
    "state": {"en": "State", "ta": "மாநிலம்"},
    "language_label": {"en": "Language", "ta": "மொழி"},
    "generated_on": {"en": "Generated On", "ta": "உருவாக்கப்பட்ட தேதி"},
    "time": {"en": "Time", "ta": "நேரம்"},
    "en": {"en": "English", "ta": "ஆங்கிலம்"},
    "ta": {"en": "Tamil", "ta": "தமிழ்"},

    # 2. Farmer Profile
    "farmer_details": {"en": "Farmer Profile", "ta": "விவசாயி விவரம்"},
    "name": {"en": "Farmer Name", "ta": "விவசாயி பெயர்"},
    "age": {"en": "Age", "ta": "வயது"},
    "education": {"en": "Education Level", "ta": "கல்வி நிலை"},
    "land_area": {"en": "Land Size", "ta": "நில அளவு"},
    "crops": {"en": "Primary Crop", "ta": "முக்கிய பயிர்"},
    "irrigation": {"en": "Irrigation Method", "ta": "பாசன முறை"},
    "smartphone": {"en": "Smartphone Availability", "ta": "ஸ்மார்ட்போன் பயன்பாடு"},
    "internet": {"en": "Internet Access", "ta": "இணைய அணுகல்"},

    # 3. Score
    "adoption_score_section": {"en": "Technology Adoption Score", "ta": "தொழில்நுட்ப ஏற்றுக்கொள்ளல் மதிப்பெண்"},
    "score": {"en": "Score", "ta": "மதிப்பெண்"},
    "category": {"en": "Category", "ta": "வகை"},
    "explanation_title": {"en": "Explanation:", "ta": "விளக்கம்:"},
    "score_explanation": {"en": "This score represents the farmer’s current adoption of modern agricultural technologies.", "ta": "இந்த மதிப்பெண் விவசாயி பயன்படுத்தும் நவீன தொழில்நுட்பங்களின் அளவை காட்டுகிறது."},

    # 4. AI Insights
    "ai_insights": {"en": "AI Insights", "ta": "AI பகுப்பாய்வு"},
    
    # 5. Recommended Technologies
    "recommendations": {"en": "Recommended Technologies", "ta": "பரிந்துரைக்கப்படும் தொழில்நுட்பங்கள்"},

    # 6. Crop Recommendations
    "crop_recommendations": {"en": "Crop Recommendations", "ta": "பயிர் பரிந்துரைகள்"},

    # 7. Schemes
    "schemes": {"en": "Eligible Government Schemes", "ta": "தகுதியான அரசு திட்டங்கள்"},

    # 8. Summary
    "summary": {"en": "Summary", "ta": "சுருக்கம்"},
    "summary_text": {"en": "Based on the farmer’s responses, technology adoption is currently low. Implementing the recommended technologies and utilizing government schemes can significantly improve farm productivity.", "ta": "விவசாயி அளித்த தகவல்களின் அடிப்படையில் தொழில்நுட்ப பயன்பாடு தற்போது குறைவாக உள்ளது. பரிந்துரைக்கப்பட்ட தொழில்நுட்பங்களையும் அரசு திட்டங்களையும் பயன்படுத்துவதன் மூலம் விளைச்சலை அதிகரிக்க முடியும்."},

    # 9. Footer
    "footer_1": {"en": "Generated by AgriNova", "ta": "AgriNova மூலம் உருவாக்கப்பட்டது"},
    "footer_2": {"en": "AI-Powered Agricultural Advisory System", "ta": "AI அடிப்படையிலான விவசாய ஆலோசனை அமைப்பு"},

    "na": {"en": "N/A", "ta": "கிடைக்கவில்லை"},
    "yes": {"en": "Yes", "ta": "ஆம்"},
    "no": {"en": "No", "ta": "இல்லை"},
    "acres": {"en": "Acres", "ta": "ஏக்கர்"}
}

DISTRICT_MAP_EN = [
    'Ariyalur', 'Chengalpattu', 'Chennai', 'Coimbatore', 'Cuddalore', 'Dharmapuri',
    'Dindigul', 'Erode', 'Kallakurichi', 'Kanchipuram', 'Kanyakumari', 'Karur',
    'Krishnagiri', 'Madurai', 'Mayiladuthurai', 'Nagapattinam', 'Namakkal', 'Nilgiris',
    'Perambalur', 'Pudukkottai', 'Ramanathapuram', 'Ranipet', 'Salem', 'Sivaganga',
    'Tenkasi', 'Thanjavur', 'Theni', 'Thoothukudi', 'Tiruchirappalli', 'Tirunelveli',
    'Tirupathur', 'Tiruppur', 'Tiruvallur', 'Tiruvannamalai', 'Tiruvarur', 'Vellore',
    'Viluppuram', 'Virudhunagar'
]
DISTRICT_MAP_TA = [
    'அரியலூர்', 'செங்கல்பட்டு', 'சென்னை', 'கோயம்புத்தூர்', 'கடலூர்', 'தர்மபுரி',
    'திண்டுக்கல்', 'ஈரோடு', 'கள்ளக்குறிச்சி', 'காஞ்சிபுரம்', 'கன்னியாகுமரி', 'கரூர்',
    'கிருஷ்ணகிரி', 'மதுரை', 'மயிலாடுதுறை', 'நாகப்பட்டினம்', 'நாமக்கல்', 'நீலகிரி',
    'பெரம்பலூர்', 'புதுக்கோட்டை', 'ராமநாதபுரம்', 'ராணிப்பேட்டை', 'சேலம்', 'சிவகங்கை',
    'தென்காசி', 'தஞ்சாவூர்', 'தேனி', 'தூத்துக்குடி', 'திருச்சி', 'திருநெல்வேலி',
    'திருப்பத்தூர்', 'திருப்பூர்', 'திருவள்ளூர்', 'திருவண்ணாமலை', 'திருவாரூர்', 'வேலூர்',
    'விழுப்புரம்', 'விருதுநகர்'
]

VALUE_TRANSLATIONS = {
    "Owned": "சொந்தமானது",
    "Leased": "குத்தகை",
    "Progressive": "முற்போக்கானவர்",
    "Traditional": "பாரம்பரியமானவர்",
    "High": "அதிகம்",
    "Medium": "நடுத்தரம்",
    "Low": "குறைவு",
    "None": "இல்லை",
    "Borewell": "ஆழ்துளை கிணறு",
    "River": "ஆறு",
    "Canal": "கால்வாய்",
    "Rainfed": "மழைநீர்",
    "Paddy": "நெல்",
    "Sugar Cane": "கரும்பு",
    "Rice": "அரிசி",
    "Cotton": "பருத்தி",
    "Turmeric": "மஞ்சள்",
    "Banana": "வாழை"
}

logger = logging.getLogger(__name__)

class PDFReportGenerator:
    def __init__(self):
        current_dir = os.path.dirname(os.path.abspath(__file__))
        self.font_path = os.path.join(current_dir, "..", "NotoSansTamil-Regular.ttf")
        self.tamil_font_registered = os.path.exists(self.font_path)
        
    def t(self, key, lang):
        return REPORT_TRANSLATIONS.get(key, {}).get(lang, key)
    
    def vt(self, value, lang):
        if lang != 'ta' or not value:
            return str(value) if value is not None else ""
        if isinstance(value, list):
            return ", ".join([VALUE_TRANSLATIONS.get(str(v), str(v)) for v in value])
        return VALUE_TRANSLATIONS.get(str(value), str(value))

    def resolve_district(self, district_value, lang):
        if not district_value:
            return ""
        d = str(district_value).strip()
        if d in DISTRICT_MAP_TA:
            idx = DISTRICT_MAP_TA.index(d)
            return DISTRICT_MAP_TA[idx] if lang == 'ta' else DISTRICT_MAP_EN[idx]
        if d in DISTRICT_MAP_EN:
            idx = DISTRICT_MAP_EN.index(d)
            return DISTRICT_MAP_TA[idx] if lang == 'ta' else DISTRICT_MAP_EN[idx]
        return d

    def generate_report(self, farmer_data, user_data, adoption_result, recommendations, schemes, language='en'):
        lang = language if language in ['en', 'ta'] else 'en'
        
        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        pw = pdf.epw # Explicitly use the effective page width to prevent wrap width bugs!
        
        # Setup fonts
        if self.tamil_font_registered:
            pdf.add_font("NotoSansTamil", style="", fname=self.font_path)
            # FPDF uses the regular font for bold if we map it to 'B', avoiding missing file errors
            pdf.add_font("NotoSansTamil", style="B", fname=self.font_path)
            pdf.add_font("NotoSansTamil", style="I", fname=self.font_path)
            base_font = "NotoSansTamil"
        else:
            base_font = "Helvetica"
            
        def set_title():
            pdf.set_font(base_font, 'B', 18)
            pdf.set_text_color(45, 80, 22)
            
        def set_header():
            pdf.set_font(base_font, 'B', 14)
            pdf.set_text_color(74, 124, 44)
            
        def set_body():
            pdf.set_font(base_font, '', 11)
            pdf.set_text_color(0, 0, 0)
            
        def set_footer():
            pdf.set_font(base_font, 'I' if lang=='en' else '', 9)
            pdf.set_text_color(128, 128, 128)

        now = datetime.now()
        ta_months = {
            '01': 'ஜனவரி', '02': 'பிப்ரவரி', '03': 'மார்ச்',
            '04': 'ஏப்ரல்', '05': 'மே', '06': 'ஜூன்',
            '07': 'ஜூலை', '08': 'ஆகஸ்ட்', '09': 'செப்டம்பர்',
            '10': 'அக்டோபர்', '11': 'நவம்பர்', '12': 'டிசம்பர்'
        }
        if lang == 'ta':
            day = now.strftime('%d')
            month_num = now.strftime('%m')
            year = now.strftime('%Y')
            date_str = f"{day} {ta_months.get(month_num, month_num)} {year}"
            hour = now.strftime('%I:%M')
            ampm = 'காலை' if now.strftime('%p') == 'AM' else 'மாலை'
            time_str = f"{hour} {ampm}"
        else:
            date_str = now.strftime('%d %b %Y')
            time_str = now.strftime('%I:%M %p')

        def add_bullet(text):
            set_body()
            # Explicitly force newline before every multi_cell to guarantee X is safely at LMARGIN!
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(pw, 8, "  - " + text)

        # 1. Header
        set_title()
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(pw, 10, self.t("title", lang))
        pdf.ln(5)

        set_body()
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(pw, 6, f"{self.t('farmer', lang)}: {user_data.get('name')}")
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(pw, 6, f"{self.t('district', lang)}: {self.resolve_district(user_data.get('district'), lang)}")
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(pw, 6, f"{self.t('language_label', lang)}: {self.t(lang, lang)}")
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(pw, 6, f"{self.t('generated_on', lang)}: {date_str}")
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(pw, 6, f"{self.t('time', lang)}: {time_str}")
        pdf.ln(5)

        # 2. Farmer Profile
        set_header()
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(pw, 8, self.t("farmer_details", lang))
        pdf.ln(2)
        
        farmer_name = user_data.get('name') or (self.t('na', lang))
        add_bullet(f"{self.t('name', lang)}: {farmer_name}")
        age_val = farmer_data.get('age')
        add_bullet(f"{self.t('age', lang)}: {age_val if age_val else self.t('na', lang)}")
        edu_raw = farmer_data.get('education')
        edu_val = self.vt(edu_raw, lang) if edu_raw else self.t('na', lang)
        add_bullet(f"{self.t('education', lang)}: {edu_val}")
        land = farmer_data.get('land_area')
        add_bullet(f"{self.t('land_area', lang)}: {land if land else self.t('na', lang)} {self.t('acres', lang)}")
        
        raw_crops = farmer_data.get('crop_type', farmer_data.get('crops'))
        if isinstance(raw_crops, list):
            raw_crops = [c for c in raw_crops if c and str(c).strip()]
        crop_val = self.vt(raw_crops, lang) if raw_crops else self.t('na', lang)
        add_bullet(f"{self.t('crops', lang)}: {crop_val}")
        
        irr_raw = farmer_data.get('irrigation_source')
        irr_val = self.vt(irr_raw, lang) if irr_raw else self.t('na', lang)
        add_bullet(f"{self.t('irrigation', lang)}: {irr_val}")
        
        sm_status_key = 'yes' if farmer_data.get('has_smartphone') else 'no'
        int_status_key = 'yes' if farmer_data.get('has_internet') else 'no'
        add_bullet(f"{self.t('smartphone', lang)}: {self.t(sm_status_key, lang)}")
        add_bullet(f"{self.t('internet', lang)}: {self.t(int_status_key, lang)}")
        pdf.ln(5)

        # 3. Score
        set_header()
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(pw, 8, self.t("adoption_score_section", lang))
        pdf.ln(2)
        add_bullet(f"{self.t('score', lang)}: {adoption_result.get('adoption_score', 0)}%")
        add_bullet(f"{self.t('category', lang)}: {self.vt(adoption_result.get('adoption_category', 'N/A'), lang)}")
        pdf.ln(2)
        
        set_body()
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(pw, 6, self.t("explanation_title", lang) if lang == 'ta' else "Explanation:")
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(pw, 6, self.t("score_explanation", lang))
        pdf.ln(5)

        # 4. AI Insights
        set_header()
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(pw, 8, self.t("ai_insights", lang))
        pdf.ln(2)
        if lang == 'en':
            add_bullet("Low technology usage detected" if (len(farmer_data.get('technologies_used', [])) < 2) else "Good technology usage detected")
            add_bullet("Limited awareness of government schemes" if (len(farmer_data.get('schemes_aware', [])) < 2) else "Good awareness of government schemes")
            add_bullet("Potential to improve farm productivity")
        else:
            add_bullet("தொழில்நுட்ப பயன்பாடு குறைவாக உள்ளது" if (len(farmer_data.get('technologies_used', [])) < 2) else "தொழில்நுட்ப பயன்பாடு நன்றாக உள்ளது")
            add_bullet("அரசு திட்டங்களின் விழிப்புணர்வு குறைவு" if (len(farmer_data.get('schemes_aware', [])) < 2) else "அரசு திட்டங்களின் விழிப்புணர்வு நன்றாக உள்ளது")
            add_bullet("விளைச்சலை அதிகரிக்கும் வாய்ப்பு உள்ளது")
        pdf.ln(5)
            
        # 5. Recommended Technologies (Tamil only)
        if lang == 'ta':
            set_header()
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(pw, 8, self.t("recommendations", lang))
            pdf.ln(2)
            tech_list = recommendations.get('technologies', []) if recommendations else []
            if tech_list:
                for t_item in tech_list[:4]:
                    name = t_item.get('tech_ta') or t_item.get('tech_en', 'N/A')
                    desc = t_item.get('description_ta', '')
                    cost = t_item.get('cost_ta', '')
                    scheme = t_item.get('scheme_ta', '')
                    add_bullet(name)
                    set_body()
                    if desc: 
                        pdf.set_x(pdf.l_margin)
                        pdf.multi_cell(pw, 6, f"    {desc}")
                    if cost: 
                        pdf.set_x(pdf.l_margin)
                        pdf.multi_cell(pw, 6, f"    செலவு: {cost}")
                    if scheme: 
                        pdf.set_x(pdf.l_margin)
                        pdf.multi_cell(pw, 6, f"    திட்டம்: {scheme}")
                    pdf.ln(2)
            else:
                add_bullet(self.t("na", lang))
            pdf.ln(5)

        # 6. Crop Recommendations (Tamil only)
        if lang == 'ta':
            set_header()
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(pw, 8, self.t("crop_recommendations", lang))
            pdf.ln(2)
            crop_list = recommendations.get('crops', []) if recommendations else []
            if crop_list:
                for c_item in crop_list[:4]:
                    name = c_item.get('crop_ta') or c_item.get('crop_en', 'N/A')
                    add_bullet(name)
            else:
                add_bullet(self.t("na", lang))
            pdf.ln(5)

        # 7. Schemes
        set_header()
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(pw, 8, self.t("schemes", lang))
        pdf.ln(2)
        if schemes:
            for s_item in schemes:
                name = s_item.get('name_ta') if lang == 'ta' else s_item.get('name')
                add_bullet(name or s_item.get('name', 'N/A'))
        else:
            add_bullet(self.t("na", lang))
        pdf.ln(5)

        # 8. Summary
        set_header()
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(pw, 8, self.t("summary", lang))
        pdf.ln(2)
        set_body()
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(pw, 6, self.t("summary_text", lang))
        pdf.ln(10)

        # 9. Footer
        set_footer()
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(pw, 5, self.t("footer_1", lang), align='C')
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(pw, 5, self.t("footer_2", lang), align='C')

        # Output
        if lang == 'ta':
            filename = f"AgriNova_உழவர்_அறிக்கை_{user_data.get('user_id', 'unknown')}.pdf"
        else:
            filename = f"AgriNova_Farmer_Report_{user_data.get('user_id', 'unknown')}.pdf"
            
        filepath = os.path.join('reports', filename)
        os.makedirs('reports', exist_ok=True)
            
        pdf.output(filepath)
        return filepath

# Global PDF generator instance
pdf_generator = PDFReportGenerator()
