import os
import logging
from datetime import datetime

# Enable complex script shaping (MUST be done before importing other reportlab modules)
from reportlab import rl_config
rl_config.allow_shaping = True
rl_config.shaper = 'harfbuzz'

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak, ListFlowable, ListItem
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

logger = logging.getLogger(__name__)

REPORT_TRANSLATIONS = {
    # 1. Header
    "title": {"en": "AgriNova – Farmer Technology Adoption Report", "ta": "AgriNova – விவசாய தொழில்நுட்ப ஏற்றுக்கொள்ளல் அறிக்கை"},
    "farmer": {"en": "Farmer", "ta": "விவசாயி"},
    "district": {"en": "District", "ta": "மாவட்டம்"},
    "state": {"en": "State", "ta": "மாநிலம்"},
    "language_label": {"en": "Language", "ta": "மொழி"},
    "generated_on": {"en": "Generated On", "ta": "உருவாக்கப்பட்ட தேதி"},
    "time": {"en": "Time", "ta": "நேரம்"},
    "en": {"en": "English", "ta": "ஆங்கிலம்"},
    "ta": {"en": "Tamil", "ta": "தமிழ்"},

    # 2. Farmer Profile
    "farmer_details": {"en": "Farmer Profile", "ta": "விவசாயி விவரம்"},
    "name": {"en": "Farmer Name", "ta": "விவசாயி பெயர்"},
    "age": {"en": "Age", "ta": "வயது"},
    "education": {"en": "Education Level", "ta": "கல்வி நிலை"},
    "land_area": {"en": "Land Size", "ta": "நில அளவு"},
    "crops": {"en": "Primary Crop", "ta": "முக்கிய பயிர்"},
    "irrigation": {"en": "Irrigation Method", "ta": "பாசன முறை"},
    "smartphone": {"en": "Smartphone Availability", "ta": "ஸ்மார்ட்போன் பயன்பாடு"},
    "internet": {"en": "Internet Access", "ta": "இணைய அணுகல்"},

    # 3. Score
    "adoption_score_section": {"en": "Technology Adoption Score", "ta": "தொழில்நுட்ப ஏற்றுக்கொள்ளல் மதிப்பெண்"},
    "score": {"en": "Score", "ta": "மதிப்பெண்"},
    "category": {"en": "Category", "ta": "வகை"},
    "explanation_title": {"en": "Explanation:", "ta": "விளக்கம்:"},
    "score_explanation": {"en": "This score represents the farmer’s current adoption of modern agricultural technologies.", "ta": "இந்த மதிப்பெண் விவசாயி பயன்படுத்தும் நவீன தொழில்நுட்பங்களின் அளவை காட்டுகிறது."},

    # 4. AI Insights
    "ai_insights": {"en": "AI Insights", "ta": "AI பகுப்பாய்வு"},
    
    # 5. Recommended Technologies
    "recommendations": {"en": "Recommended Technologies", "ta": "பரிந்துரைக்கப்படும் தொழில்நுட்பங்கள்"},

    # 6. Crop Recommendations
    "crop_recommendations": {"en": "Crop Recommendations", "ta": "பயிர் பரிந்துரைகள்"},

    # 7. Schemes
    "schemes": {"en": "Eligible Government Schemes", "ta": "தகுதியான அரசு திட்டங்கள்"},

    # 8. Summary
    "summary": {"en": "Summary", "ta": "சுருக்கம்"},
    "summary_text": {"en": "Based on the farmer’s responses, technology adoption is currently low. Implementing the recommended technologies and utilizing government schemes can significantly improve farm productivity.", "ta": "விவசாயி அளித்த தகவல்களின் அடிப்படையில் தொழில்நுட்ப பயன்பாடு தற்போது குறைவாக உள்ளது. பரிந்துரைக்கப்பட்ட தொழில்நுட்பங்களையும் அரசு திட்டங்களையும் பயன்படுத்துவதன் மூலம் விளைச்சலை அதிகரிக்க முடியும்."},

    # 9. Footer
    "footer_1": {"en": "Generated by AgriNova", "ta": "AgriNova மூலம் உருவாக்கப்பட்டது"},
    "footer_2": {"en": "AI-Powered Agricultural Advisory System", "ta": "AI அடிப்படையிலான விவசாய ஆலோசனை அமைப்பு"},

    "na": {"en": "N/A", "ta": "கிடைக்கவில்லை"},
    "yes": {"en": "Yes", "ta": "ஆம்"},
    "no": {"en": "No", "ta": "இல்லை"},
    "acres": {"en": "Acres", "ta": "ஏக்கர்"}
}

# Bidirectional district map: Tamil <-> English
DISTRICT_MAP_EN = [
    'Ariyalur', 'Chengalpattu', 'Chennai', 'Coimbatore', 'Cuddalore', 'Dharmapuri',
    'Dindigul', 'Erode', 'Kallakurichi', 'Kanchipuram', 'Kanyakumari', 'Karur',
    'Krishnagiri', 'Madurai', 'Mayiladuthurai', 'Nagapattinam', 'Namakkal', 'Nilgiris',
    'Perambalur', 'Pudukkottai', 'Ramanathapuram', 'Ranipet', 'Salem', 'Sivaganga',
    'Tenkasi', 'Thanjavur', 'Theni', 'Thoothukudi', 'Tiruchirappalli', 'Tirunelveli',
    'Tirupathur', 'Tiruppur', 'Tiruvallur', 'Tiruvannamalai', 'Tiruvarur', 'Vellore',
    'Viluppuram', 'Virudhunagar'
]
DISTRICT_MAP_TA = [
    'அரியலூர்', 'செங்கல்பட்டு', 'சென்னை', 'கோயம்புத்தூர்', 'கடலூர்', 'தர்மபுரி',
    'திண்டுக்கல்', 'ஈரோடு', 'கள்ளக்குறிச்சி', 'காஞ்சிபுரம்', 'கன்னியாகுமரி', 'கரூர்',
    'கிருஷ்ணகிரி', 'மதுரை', 'மயிலாடுதுறை', 'நாகப்பட்டினம்', 'நாமக்கல்', 'நீலகிரி',
    'பெரம்பலூர்', 'புதுக்கோட்டை', 'ராமநாதபுரம்', 'ராணிப்பேட்டை', 'சேலம்', 'சிவகங்கை',
    'தென்காசி', 'தஞ்சாவூர்', 'தேனி', 'தூத்துக்குடி', 'திருச்சி', 'திருநெல்வேலி',
    'திருப்பத்தூர்', 'திருப்பூர்', 'திருவள்ளூர்', 'திருவண்ணாமலை', 'திருவாரூர்', 'வேலூர்',
    'விழுப்புரம்', 'விருதுநகர்'
]

VALUE_TRANSLATIONS = {
    # Educational logic is typically mapping string. Using str default dict matching below
    "Owned": "சொந்தமானது",
    "Leased": "குத்தகை",
    "Progressive": "முற்போக்கானவர்",
    "Traditional": "பாரம்பரியமானவர்",
    "High": "அதிகம்",
    "Medium": "நடுத்தரம்",
    "Low": "குறைவு",
    "None": "இல்லை",
    "Borewell": "ஆழ்துளை கிணறு",
    "River": "ஆறு",
    "Canal": "கால்வாய்",
    "Rainfed": "மழைநீர்",
    "Paddy": "நெல்",
    "Sugar Cane": "கரும்பு",
    "Rice": "அரிசி",
    "Cotton": "பருத்தி",
    "Turmeric": "மஞ்சள்",
    "Banana": "வாழை"
}

class PDFReportGenerator:
    def __init__(self):
        # Resolve font path relative to the script location
        current_dir = os.path.dirname(os.path.abspath(__file__))
        # The font NotoSansTamil-Regular.ttf is in the backend/ root directory
        self.font_path = os.path.join(current_dir, "..", "NotoSansTamil-Regular.ttf")
        self.tamil_font_registered = False

        if os.path.exists(self.font_path):
            try:
                # Register the font with a name we can use in styles
                pdfmetrics.registerFont(TTFont("NotoSansTamil", self.font_path))
                # Register bold/italic fallbacks to the same font file if bold file is missing
                pdfmetrics.registerFont(TTFont("NotoSansTamil-Bold", self.font_path))
                pdfmetrics.registerFontFamily("NotoSansTamil", normal="NotoSansTamil", bold="NotoSansTamil-Bold")
                
                self.tamil_font_registered = True
                logger.info(f"Successfully registered Tamil font: {self.font_path}")
            except Exception as e:
                logger.error(f"Error registering font {self.font_path}: {e}")
        else:
            logger.warning(f"Tamil font not found at {self.font_path}")
        
        self.styles = getSampleStyleSheet()

    def get_dynamic_style(self, style_name, lang):
        use_tamil = (lang == 'ta' and self.tamil_font_registered)
        base_font = "NotoSansTamil" if use_tamil else "Helvetica"
        
        style_key = f"{style_name}_{lang}"
        if style_key in self.styles:
            return self.styles[style_key]
            
        if style_name == 'CustomTitle':
            style = ParagraphStyle(
                name=style_key,
                parent=self.styles['Heading1'],
                fontName=base_font + "-Bold" if not use_tamil else "NotoSansTamil-Bold",
                fontSize=18,
                textColor=colors.HexColor('#2d5016'),
                spaceAfter=15,
                alignment=TA_LEFT
            )
        elif style_name == 'SectionHeader':
            style = ParagraphStyle(
                name=style_key,
                parent=self.styles['Heading2'],
                fontName=base_font + "-Bold" if not use_tamil else "NotoSansTamil-Bold",
                fontSize=14,
                textColor=colors.HexColor('#4a7c2c'),
                spaceAfter=10,
                spaceBefore=15,
                alignment=TA_LEFT
            )
        elif style_name == 'BodyText':
            style = ParagraphStyle(
                name=style_key,
                parent=self.styles['Normal'],
                fontName=base_font,
                fontSize=11,
                leading=16
            )
        elif style_name == 'BulletText':
            style = ParagraphStyle(
                name=style_key,
                parent=self.styles['Normal'],
                fontName=base_font,
                fontSize=11,
                leading=16,
                bulletIndent=15,
                leftIndent=30
            )
        elif style_name == 'FooterText':
            style = ParagraphStyle(
                name=style_key,
                parent=self.styles['Normal'],
                fontName=base_font + "-Oblique" if not use_tamil else base_font,
                fontSize=9,
                textColor=colors.gray,
                alignment=TA_CENTER
            )
        else:
            style = self.styles['Normal']
            
        self.styles.add(style)
        return style

    def t(self, key, lang):
        return REPORT_TRANSLATIONS.get(key, {}).get(lang, key)
    
    def vt(self, value, lang):
        if lang != 'ta' or not value:
            return str(value) if value is not None else ""
        
        if isinstance(value, list):
            return ", ".join([VALUE_TRANSLATIONS.get(str(v), str(v)) for v in value])
            
        return VALUE_TRANSLATIONS.get(str(value), str(value))

    def resolve_district(self, district_value, lang):
        """Resolve district to correct language regardless of how it's stored (Tamil or English)."""
        if not district_value:
            return ""
        d = str(district_value).strip()
        # Check if it's Tamil already
        if d in DISTRICT_MAP_TA:
            idx = DISTRICT_MAP_TA.index(d)
            return DISTRICT_MAP_TA[idx] if lang == 'ta' else DISTRICT_MAP_EN[idx]
        # Check if it's English already
        if d in DISTRICT_MAP_EN:
            idx = DISTRICT_MAP_EN.index(d)
            return DISTRICT_MAP_TA[idx] if lang == 'ta' else DISTRICT_MAP_EN[idx]
        # Unknown district - return as-is (might be garbled if font doesn't support it in English PDF)
        return d

    def generate_report(self, farmer_data, user_data, adoption_result, recommendations, schemes, language='en'):
        lang = language if language in ['en', 'ta'] else 'en'
        
        if lang == 'ta':
            filename = f"AgriNova_உழவர்_அறிக்கை_{user_data['user_id']}.pdf"
        else:
            filename = f"AgriNova_Farmer_Report_{user_data['user_id']}.pdf"
            
        filepath = os.path.join('reports', filename)
        
        if not os.path.exists('reports'):
            os.makedirs('reports')
        
        doc = SimpleDocTemplate(filepath, pagesize=A4, rightMargin=50, leftMargin=50, topMargin=50, bottomMargin=50)
        story = []
        
        title_style = self.get_dynamic_style('CustomTitle', lang)
        header_style = self.get_dynamic_style('SectionHeader', lang)
        body_style = self.get_dynamic_style('BodyText', lang)
        bullet_style = self.get_dynamic_style('BulletText', lang)
        footer_style = self.get_dynamic_style('FooterText', lang)

        def add_bullet(text):
            story.append(Paragraph(f"• {text}", bullet_style))
        
        now = datetime.now()
        # Full Tamil month map
        ta_months = {
            '01': 'ஜனவரி', '02': 'பிப்ரவரி', '03': 'மார்ச்',
            '04': 'ஏப்ரல்', '05': 'மே', '06': 'ஜூன்',
            '07': 'ஜூலை', '08': 'ஆகஸ்ட்', '09': 'செப்டம்பர்',
            '10': 'அக்டோபர்', '11': 'நவம்பர்', '12': 'டிசம்பர்'
        }
        if lang == 'ta':
            day = now.strftime('%d')
            month_num = now.strftime('%m')
            year = now.strftime('%Y')
            date_str = f"{day} {ta_months.get(month_num, month_num)} {year}"
            hour = now.strftime('%I:%M')
            ampm = 'காலை' if now.strftime('%p') == 'AM' else 'மாலை'
            time_str = f"{hour} {ampm}"
        else:
            date_str = now.strftime('%d %b %Y')
            time_str = now.strftime('%I:%M %p')

        # 1. Header
        story.append(Paragraph(self.t("title", lang), title_style))
        story.append(Spacer(1, 0.1*inch))
        
        if lang == 'en':
            story.append(Paragraph(f"{self.t('farmer', lang)}: {user_data.get('name')}", body_style))
            story.append(Paragraph(f"{self.t('district', lang)}: {self.resolve_district(user_data.get('district'), lang)}", body_style))
            story.append(Paragraph(f"{self.t('language_label', lang)}: {self.t('en', lang)}", body_style))
            story.append(Paragraph(f"{self.t('generated_on', lang)}: {now.strftime('%d %b %Y')}", body_style))
            story.append(Paragraph(f"{self.t('time', lang)}: {time_str}", body_style))
        else:
            story.append(Paragraph(f"{self.t('farmer', lang)}: {user_data.get('name')}", body_style))
            story.append(Paragraph(f"{self.t('district', lang)}: {self.resolve_district(user_data.get('district'), lang)}", body_style))
            story.append(Paragraph(f"{self.t('language_label', lang)}: {self.t('ta', lang)}", body_style))
            story.append(Paragraph(f"{self.t('generated_on', lang)}: {date_str}", body_style))
            story.append(Paragraph(f"{self.t('time', lang)}: {time_str}", body_style))

        story.append(Spacer(1, 0.2*inch))
        
        # 2. Farmer Profile
        story.append(Paragraph(self.t("farmer_details", lang), header_style))
        farmer_name = user_data.get('name') or (self.t('na', lang))
        add_bullet(f"{self.t('name', lang)}: {farmer_name}")
        age_val = farmer_data.get('age')
        add_bullet(f"{self.t('age', lang)}: {age_val if age_val else self.t('na', lang)}")
        edu_raw = farmer_data.get('education')
        edu_val = self.vt(edu_raw, lang) if edu_raw else self.t('na', lang)
        add_bullet(f"{self.t('education', lang)}: {edu_val}")
        land = farmer_data.get('land_area')
        add_bullet(f"{self.t('land_area', lang)}: {land if land else self.t('na', lang)} {self.t('acres', lang)}")
        # Clean crops: filter blanks from list
        raw_crops = farmer_data.get('crop_type', farmer_data.get('crops'))
        if isinstance(raw_crops, list):
            raw_crops = [c for c in raw_crops if c and str(c).strip()]
        crop_val = self.vt(raw_crops, lang) if raw_crops else self.t('na', lang)
        add_bullet(f"{self.t('crops', lang)}: {crop_val}")
        irr_raw = farmer_data.get('irrigation_source')
        irr_val = self.vt(irr_raw, lang) if irr_raw else self.t('na', lang)
        add_bullet(f"{self.t('irrigation', lang)}: {irr_val}")
        sm_status_key = 'yes' if farmer_data.get('has_smartphone') else 'no'
        int_status_key = 'yes' if farmer_data.get('has_internet') else 'no'
        add_bullet(f"{self.t('smartphone', lang)}: {self.t(sm_status_key, lang)}")
        add_bullet(f"{self.t('internet', lang)}: {self.t(int_status_key, lang)}")

        story.append(Spacer(1, 0.2*inch))

        # 3. Score
        story.append(Paragraph(self.t("adoption_score_section", lang), header_style))
        add_bullet(f"{self.t('score', lang)}: {adoption_result.get('adoption_score', 0)}%")
        add_bullet(f"{self.t('category', lang)}: {self.vt(adoption_result.get('adoption_category', 'N/A'), lang)}")
        story.append(Spacer(1, 0.1*inch))
        
        story.append(Paragraph(self.t("explanation_title", lang) if lang == 'ta' else "Explanation:", body_style))
        story.append(Paragraph(self.t("score_explanation", lang), body_style))

        story.append(Spacer(1, 0.2*inch))

        # 4. AI Insights
        story.append(Paragraph(self.t("ai_insights", lang), header_style))
        if lang == 'en':
            add_bullet("Low technology usage detected" if (len(farmer_data.get('technologies_used', [])) < 2) else "Good technology usage detected")
            add_bullet("Limited awareness of government schemes" if (len(farmer_data.get('schemes_aware', [])) < 2) else "Good awareness of government schemes")
            add_bullet("Potential to improve farm productivity")
        else:
            add_bullet("தொழில்நுட்ப பயன்பாடு குறைவாக உள்ளது" if (len(farmer_data.get('technologies_used', [])) < 2) else "தொழில்நுட்ப பயன்பாடு நன்றாக உள்ளது")
            add_bullet("அரசு திட்டங்களின் விழிப்புணர்வு குறைவு" if (len(farmer_data.get('schemes_aware', [])) < 2) else "அரசு திட்டங்களின் விழிப்புணர்வு நன்றாக உள்ளது")
            add_bullet("விளைச்சலை அதிகரிக்கும் வாய்ப்பு உள்ளது")
            
        story.append(Spacer(1, 0.2*inch))

        # 5. Recommended Technologies (Tamil only with name+description; English skipped as per requirements)
        if lang == 'ta':
            story.append(Paragraph(self.t("recommendations", lang), header_style))
            tech_list = recommendations.get('technologies', []) if recommendations else []
            if tech_list:
                for t_item in tech_list[:4]:
                    name = t_item.get('tech_ta') or t_item.get('tech_en', 'N/A')
                    desc = t_item.get('description_ta', '')
                    cost = t_item.get('cost_ta', '')
                    scheme = t_item.get('scheme_ta', '')
                    line_parts = [name]
                    if desc: line_parts.append(f"   {desc}")
                    if cost: line_parts.append(f"   செலவு: {cost}")
                    if scheme: line_parts.append(f"   திட்டம்: {scheme}")
                    add_bullet(name)
                    if desc: story.append(Paragraph(f"   {desc}", body_style))
                    if cost: story.append(Paragraph(f"   செலவு: {cost}", body_style))
                    if scheme: story.append(Paragraph(f"   திட்டம்: {scheme}", body_style))
                    story.append(Spacer(1, 0.05*inch))
            else:
                add_bullet(self.t("na", lang))
            story.append(Spacer(1, 0.2*inch))

        # 6. Crop Recommendations (Tamil only)
        if lang == 'ta':
            story.append(Paragraph(self.t("crop_recommendations", lang), header_style))
            crop_list = recommendations.get('crops', []) if recommendations else []
            if crop_list:
                for c_item in crop_list[:4]:
                    name = c_item.get('crop_ta') or c_item.get('crop_en', 'N/A')
                    add_bullet(name)
            else:
                add_bullet(self.t("na", lang))
            story.append(Spacer(1, 0.2*inch))

        story.append(Spacer(1, 0.2*inch))
        
        # 7. Schemes
        story.append(Paragraph(self.t("schemes", lang), header_style))
        if schemes:
            for s_item in schemes:
                name = s_item.get('name_ta') if lang == 'ta' else s_item.get('name')
                add_bullet(name or s_item.get('name', 'N/A'))
        else:
            add_bullet(self.t("na", lang))

        story.append(Spacer(1, 0.2*inch))

        # 8. Summary
        story.append(Paragraph(self.t("summary", lang), header_style))
        story.append(Paragraph(self.t("summary_text", lang), body_style))

        # 9. Footer
        story.append(Spacer(1, 0.5*inch))
        story.append(Paragraph(self.t("footer_1", lang), footer_style))
        story.append(Paragraph(self.t("footer_2", lang), footer_style))

        # Build PDF
        try:
            doc.build(story)
        except Exception as e:
            print(f"Error building PDF: {e}")
            raise e
        
        return filepath

# Global PDF generator instance
pdf_generator = PDFReportGenerator()
